### ISSUE TITLE
Last steps: Close first part

### ISSUE THREAD

**Issue by UserStefan** [guaka/hitchticker#21]
Hey guys,

the two races are done. Thanks for the work so far! I think it went pretty well. We have some entertaining tweets and the basic functioning is secured. 

I would ask to make a line here and finish the last things, which are in my opinion:
1. [ ] Creating a functioning registration. Seems like all dudes are posting anonymous. Not sure if it should be obligatory, but it shouldn´t be like this. #22
2. [ ] Fixing the SMS-Feature (regarding to point 1, seems like this is not working properly, afaik from Ben and the tweets) #23
3. [x] Implementing groups to tweet for different issues (it is unsorted, need some more structure for better overview. also i would like to stream my own trip). #24
4. [x] We need an invoice (to: benjamin.nopper@t-online.de, adressed to Deutsche Trampsport Gemeinschaft. Platschi can transfer the money). DONE @guaka
5. [x] Transferring the telephone number to DTSG, or at least the monthly costs. We also can transfer an amount of money to cover the next couple of months/years and leave it, how it is. Don´t know who registered it so far, which provider and how much it costs. #20 

I also asked Philipp (who created the abgefahren ticker) and he said, that he will have a look at it, when he has some more time and is free to work.

Let´ do this and then see, how it is going. When everything is done, i would like to introduce the ticker to the public crowd.

Greetz from Bolivia,

Stefan

**Comment by simison** [comment]
@guaka, could you add @mrtweek to the repo?

**Comment by guaka** [comment]
added @MrTweek

**Comment by guaka** [comment]
probably best to get back to these points when meeting with @badmadrabbit some time

**Comment by badmadrabbit** [comment]
Yeah, let's get our heads together these days!

**Comment by platschi** [comment]
Any updates? Please someone get in contact with me regarding the invoice. Kind of semi-urgent :)

**Comment by guaka** [comment]
@platschi I replied to your email now.

**Comment by simison** [comment]
FYI, made some quick changes to make this work better with mobile.

Connecting the phone number to the user would be the last most important thing to implement.

**Comment by UserStefan** [comment]
Okay guys, how is it going? Which parts are open, which not? We close our EU application on the 31st of september and i would like to have this project finished. I also would do a small promotion afterwards and introduce the ticker to the community. Even write a hitchwiki article about it. :) But before we should tik those point off please.

**Comment by guaka** [comment]
- Created issues #22 #23 #24 #25, please add more info
- Created milestone https://github.com/guaka/hitchticker/milestones/end%20of%20September

Also possible to create issues for "small promotion" and "hitchwiki article" for this milestone

**Comment by UserStefan** [comment]
All this issues are confusing me now. But i try to comment on them.
